"""Integration test: 2-level Brownian-oscillator HEOM dynamics.

Side-effect-free port of ``examples/basic/brownian_oscillator_heom.py``.
Reference values pinned at five time points generated by the icpx + Eigen
build (no MKL, no CUDA).  The reference matches the SI v0.5 result to ~1e-11.
"""

import numpy as np
import pytest

from pyheom import HEOMSolver, noise_decomposition, Brown, unit


# (time, rho_00) reference points from population_master_eigen.dat
REFERENCE = [
    ( 0.000, 1.0),
    ( 4.975, 0.7569977275059762),
    ( 9.975, 0.4763035686571218),
    (14.975, 0.3367025650883704),
    (24.975, 0.2777561128728375),
]
TOL = 1e-10


pytestmark = pytest.mark.integration


def _build_solver():
    lambda_0 = 0.01
    omega_0  = 1.0
    zeta     = 0.5
    T        = 1.0
    n_tiers  = 5

    J = Brown(lambda_0, zeta, omega_0)
    corr = noise_decomposition(J, T=T, type_ltc='psd', n_psd=1, type_psd='n-1/n')

    omega_1 = np.sqrt(omega_0**2 - zeta**2 * 0.25)
    H = np.array([[omega_1, 0.0], [0.0, 0.0]], dtype=np.complex128)
    corr.V = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=np.complex128)

    return HEOMSolver(
        H, [corr],
        space='liouville', format='dense', engine='eigen',
        liouville_order='C', solver='lsrk4',
        engine_args=dict(),
        n_tiers=n_tiers,
        n_inner_threads=1,
        n_outer_threads=1,
    )


def test_brownian_2level_population_dynamics():
    qme = _build_solver()
    rho_0 = np.zeros((2, 2), dtype=np.complex128)
    rho_0[0, 0] = 1.0

    target_times  = [t for t, _ in REFERENCE if t > 0.0]
    callback_dt   = 2.5e-2
    t_list        = np.arange(0.0, target_times[-1] + callback_dt * 0.5, callback_dt)

    captured = {}

    def callback(t):
        for ref_t in target_times:
            if ref_t in captured:
                continue
            if abs(t - ref_t) < callback_dt * 0.51:
                captured[ref_t] = float(qme.rho[0, 0].real)

    qme.solve(rho_0, t_list, callback=callback, dt=0.25e-2)

    # initial value
    assert REFERENCE[0][1] == 1.0  # sanity

    for ref_t, ref_val in REFERENCE[1:]:
        assert ref_t in captured, f"callback missed t={ref_t}"
        assert captured[ref_t] == pytest.approx(ref_val, abs=TOL), \
            f"t={ref_t}: got {captured[ref_t]}, expected {ref_val}"


def test_solver_does_not_write_files(tmp_path, monkeypatch):
    """Regression guard: a plain solve must not create files anywhere."""
    monkeypatch.chdir(tmp_path)

    qme = _build_solver()
    rho_0 = np.zeros((2, 2), dtype=np.complex128)
    rho_0[0, 0] = 1.0
    t_list = np.linspace(0.0, 1.0, 11)

    qme.solve(rho_0, t_list, dt=0.25e-2)

    leftover = list(tmp_path.iterdir())
    assert leftover == [], f"unexpected files created: {leftover}"
